name: Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components (API 34)
        run: |
          sdkmanager --install "platform-tools" "cmdline-tools;latest"                      "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Install Gradle & generate wrapper
        shell: bash
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle wrapper --gradle-version 8.7

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew clean assembleDebug --no-daemon

      - name: Show build outputs
        run: |
          echo "Listing build outputs:"
          ls -R app/build/outputs || true
          echo "Find APKs:"
          find app/build -name "*.apk" -print || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/**/*.apk
          if-no-files-found: warn
